### ISSUE TITLE
Suggestion for roadmap: User Based Package Management

### ISSUE THREAD

**Issue by serhanekmekci** [CarbsLinux/kiss#4]
Check: 

http://www.linuxfromscratch.org/hints/downloads/files/more_control_and_pkg_man.txt

https://github.com/ericherman/package-users

**Comment by cemkeylan** [comment]
Thank you for this link, I have found some of those points are really helpful. 
However, I would prefer not having user-based package management as it tends to
make things more complex to manage the system. I see that the main point of this
user-based management system is handling conflicts and managing who can maintain
specific software in the system.

Since kiss can resolve conflicts with the alternatives system (or error out if
you specify KISS_CHOICE=0 in your environment), we do not need package users to
handle these conflict errors by permission. Regardless, this way of handling is
not ideal, because

- You either have to add users for each package, which will make the system 
  extremely complex. I currently have 326 packages in my system, with 463
  file conflicts easily resolved by the package manager's alternatives system.
  If I were to resolve this by package users, it would take so many time.
- If you don't have users for each package but for each category, you will not
  know if a package of the same category overwrites a file from another package.

Setting up users to maintain specific software, in my opinion, should be configured
in a sudo/doas configuration instead of the package manager itself. Unlike LFS,
where you have to manage each software manually, kiss has repositories. Now, you
might not be using the repositories from Carbs Linux, or KISS Linux, but a system
admin can add repositories for different users and add it to his/her `KISS_PATH`.
Those user can create package directories that they manage manually. Once they
are done, a sysadmin can build packages maintained by other users in the system.

I think these sum up my thoughts on the matter, thanks for bringing it to my
attention.

On 20/05/15 12:28PM, serhanekmekci wrote:
> Check: 
> 
> http://www.linuxfromscratch.org/hints/downloads/files/more_control_and_pkg_man.txt
> 
> https://github.com/ericherman/package-users
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/CarbsLinux/kiss/issues/4

-- 
Best Regards,
Cem Keylan
